DROP TABLE IF EXISTS ARTIST;
DROP TABLE IF EXISTS CONCERT;

CREATE TABLE ARTIST(ID INT PRIMARY KEY, NAME VARCHAR(255), GENRE VARCHAR(255));
INSERT INTO ARTIST VALUES(1, 'Cher Lloyd', 'Pop');
INSERT INTO ARTIST VALUES(2, 'Elysion', 'Hard Rock');
INSERT INTO ARTIST VALUES(3, 'The Lovecrave', 'Hard Rock');
INSERT INTO ARTIST VALUES(4, 'Sia', 'Pop');
INSERT INTO ARTIST VALUES(5, 'Elmore James', 'Blues');
INSERT INTO ARTIST VALUES(6, 'Willie Nelson', 'Country');
INSERT INTO ARTIST VALUES(7, 'Brad Paisley', 'Country');
INSERT INTO ARTIST VALUES(8, 'Epica', 'Hard Rock’);

CREATE TABLE CONCERT(ID INT PRIMARY KEY, DATE, GENRE VARCHAR(255));
INSERT INTO ARTIST VALUES(1, 'Cher Lloyd', 'Pop');
INSERT INTO ARTIST VALUES(2, 'Elysion', 'Hard Rock');
INSERT INTO ARTIST VALUES(3, 'The Lovecrave', 'Hard Rock');